theme: minima
title: My blog test: here is a personal touch (00)
author: Bullseye180
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A test blog from Bullseye one hundred and eighty

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
